version: "3.1"

services:
  gitlab-k8s-runner:
    image: omhq/gitlab-k8s-runner:0.0.4
    platform: linux/amd64
    working_dir: /workspace
    volumes:
      - ./job.yml:/workspace/job.yml
      - ./src:/workspace/src
      - ./scripts:/workspace/scripts
    entrypoint:
      - /bin/bash
      - -c
      - source ./scripts/init.sh
      - aws sts get-caller-identity
      - >
        exec python3 /workspace/src/main.py
        --manifest_path /workspace/job.yml
        --namespace default
        --job_name job-name
        --job_id job-id
    environment:
      REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      AWS_ROLE_ARN:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:

      DEBUG: "False"

      CLUSTER_NAME:
