version: "3.1"

services:
  gitlab-k8s-runner:
    image: omhq/gitlab-k8s-runner:0.0.4
    platform: linux/amd64
    working_dir: /workspace
    volumes:
      - ./job-busybox.yml:/workspace/job.yml
      - ./src:/workspace/src
      - ./scripts:/workspace/scripts
    entrypoint:
      - /bin/bash
      - -c
      - |
      - source ./scripts/init.sh
      - aws sts get-caller-identity
      - >
        exec python3 /workspace/src/main.py \
          --manifest_path /workspace/job.yml \
          --namespace cicd \
          --job_name job-busybox \
          --job_id 123xyz
    environment:
      REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1

      DEBUG: "False"
      CLUSTER_NAME: worker-cluster
