apiVersion: batch/v1
kind: Job
metadata:
  namespace: kubefill
spec:
  # 4 hours in seconds (4 * 60 * 60) the job will be terminated if it runs longer than this
  activeDeadlineSeconds: 14400

  # 5 minutes in seconds (5 * 60) the job will be deleted after it finishes
  ttlSecondsAfterFinished: 300

  # 1 try
  backoffLimit: 0

  template:
    metadata:
      name: ""
    spec:
      serviceAccountName: eks-worker-service-account
      restartPolicy: Never
      nodeSelector:
        node-group: default
      containers:
        - name: print-time
          image: busybox
          command: ["sh", "-c", "for i in $(seq 1 1); do date; sleep 240; done; exit 0"]
